import numpy as np
a=np.array([[1,2,3],[1,2,3]])
print("array created using list",a)
b=np.array((1,3,2))
print("array created using tuple",b)
c=np.zeros((3,4))
print("array with zeros",c)
d=np.full((3,3),6)
print("array with full",d)
e=np.random.random((2,2))
print("array with random",e)
f=np.arange(0,5,30)
print("array arrange",f)
g=np.linspace(0,5,10)
h=a.reshape(2,3)
print("reshape of an aray",h)
