import numpy as np
b=np.array((1,3,2))
print("array plus one",b+1)
b=np.array((1,3,2))
print("array sub one",b-1)
b=np.array((1,3,2))
print("array mul one",b*1)
b=np.array((1,3,2))
print("array cuberoot one",b**2)
b=np.array((1,3,2))
print("array mod one",b%2)
b=np.array((1,3,2))
print("array div one",b/2)
b=np.array((1,3,2))
print("array operand one",b& 1)

